### ISSUE TITLE
s6-sudoc: fatal: unable to get exit status from server: Operation timed out

### ISSUE THREAD

**Issue by tebra-jl** [NginxProxyManager/nginx-proxy-manager#2734] opened 2023-03-22 20:06 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

After updating from 2.9.19 to 2.9.21, docker don’t start. See log below.

**Nginx Proxy Manager Version**
2.9.21

**Operating System**
Odroid Debian OS docker
arm64

**Additional context**

Docker-compose

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - app-data:/data
      - letsencrypt:/etc/letsencrypt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  app-data:
  letsencrypt:
```

Log of docker:
```
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01_perms.sh
/package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_perms.sh: not found
cont-init: info: /etc/cont-init.d/01_perms.sh exited 127
cont-init: info: running /etc/cont-init.d/01_s6-secret-init.sh
/package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_s6-secret-init.sh: Permission denied
cont-init: info: /etc/cont-init.d/01_s6-secret-init.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service prepare: starting
❯ Checking folder structure ...
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
```

**Comment by tebra-jl** [comment] 2023-03-22 20:30
Sorry, all good now. I just restart one more time…

**Comment by molejado** [comment] 2023-03-23 06:15
Faced the same issue, docker only works when restarted again

**Comment by Bovive** [comment] 2023-03-24 15:14
Same problem here. It does work if you restart the container. It does not work when first started (ie. after a computer reboot).

**Comment by albicoccca** [comment] 2023-03-25 02:42
> 



> Same problem here. It does work if you restart the container. It does not work when first started (ie. after a computer reboot). It also doesn't work again when starting after an update. Currently on version 2.9.22. I'm not sure where these logs it refers to are located. A big problem is that the container doesn't restart on its own. It just hangs there not working until it is restarted.
> 
> This is still an issue. I would recommend opening it back up.

This is also the case for me. I have returned to 2.9.19 and can still use it normally. Continue to wait and see.

**Comment by jc21** [comment] 2023-03-26 23:05
Assuming this is happening on your existing stacks that have been running for a while, I'm guessing that the script that checks ownership at startup is taking longer than expected due to the size of your letsencrypt folder.

Certbot doesn't clean up older certs and just leaves them there after each renewal, so this folder can get filled with files although they are not too big.

The second restart would be faster if the files were fresh in storage caches, perhaps.

See the release notes for [2.9.20](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.9.20) for instructions to prune this folder.

In the meantime I'll look at fixing the timeout.

**Comment by MarkKla** [comment] 2023-03-27 13:54
Same problem here, the log says:

❯ Configuring npmuser ...
id: 'npmuser': no such user
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

**Comment by Bovive** [comment] 2023-03-27 14:03
> Assuming this is happening on your existing stacks that have been running for a while, I'm guessing that the script that checks ownership at startup is taking longer than expected due to the size of your letsencrypt folder.
> 
> Certbot doesn't clean up older certs and just leaves them there after each renewal, so this folder can get filled with files although they are not too big.
> 
> The second restart would be faster if the files were fresh in storage caches, perhaps.
> 
> See the release notes for [2.9.20](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.9.20) for instructions to prune this folder.
> 
> In the meantime I'll look at fixing the timeout.

Do you know if there are detailed instructions on how to use this for npm? I am not Docker savvy. The commands listed either give me a "no configuration file provided" or "no such container" error. Thanks!

**Comment by mikeo999** [comment] 2023-03-27 14:28
Also have the problem. Tried stopping / restart Docker. Restart Synology NAS but keeps coming back.
Because of that all my program's are not running anymore that works with the proxy so hopping you find a fix

Log:
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information

**Comment by kosmonot** [comment] 2023-03-27 15:52
The /etc/letsencrypt directories on the arm64 rpis that are timing out are not large (~125k and ~250k respectively). I've been running npm for about 18 months but use a single wildcard cert for each instance.

**Comment by amenolo** [comment] 2023-03-27 18:45
Just for pointing out that same issue (along with same workaround too) happens even starting from scratch with a brand new NPM container.

**Comment by StewartPolsky** [comment] 2023-03-27 18:57
Came here to add another vote that I am experiencing this issue

**Comment by krovs** [comment] 2023-03-27 19:19
+1

**Comment by jc21** [comment] 2023-03-27 22:13
> Fresh server install of ubuntu 22.04, new docker installed, same problem no certs, can't create a user default won't log in. Same error message as above.

I've just spun up `Ubuntu 22.04.2 LTS` amd64 with only docker installed and I don't have any problems using this config, login and changing default user works absolutely fine.

```yml
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

**Comment by thedxt** [comment] 2023-03-28 02:11
> I've put a fix up and it's available in the `github-develop` docker tag, can you please try that and let me know if you get further. Please close this if that fixes it.

the `github-develop` docker tag fixed it for me.

**Comment by jc21** [comment] 2023-03-28 05:22
Great. I'll close this for now.

FWIW the problem seems to be that chown'ing the entire contents of the `/etc/nginx` folder on some systems caused the issue.

**Closed by jc21** 2023-03-28 05:22 UTC
Labels: bug

**Comment by RickoT** [comment] 2023-03-28 15:21
Running this in a VM I also received this error, I changed to run as root but saw no change.  I noticed my CSR folder has almost 25k items... should I retain any of these or can I below away the whole folder?

**Comment by RickoT** [comment] 2023-03-28 15:51
well I moved all the data out of the folder and restarted the container but it did not fix the issue

**Comment by RickoT** [comment] 2023-03-28 16:01
The github-develop tag did not work for me I still have the same log output.  I also changed the user to run as root with the same result

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service prepare: starting
❯ Configuring npmuser ...
id: 'npmuser': no such user
❯ Checking paths ...
❯ Setting ownership ...
s6-rc: fatal: timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
```

**Comment by RickoT** [comment] 2023-03-28 17:24
I restored all of my files back to their original location and am using docker tag 2.9.22

Everything is working again

**Comment by Bovive** [comment] 2023-04-01 00:04
I still have the same problem with 

> Great. I'll close this for now.
> 
> FWIW the problem seems to be that chown'ing the entire contents of the `/etc/nginx` folder on some systems caused the issue.

I still have the same problem after updating to v2.10.2.

```
2023-03-31 18:59:57 nginx-proxy-manager-app-1  | s6-sudoc: fatal: unable to get exit status from server: Operation timed out
2023-03-31 18:59:57 nginx-proxy-manager-app-1  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
```

**Comment by GimpArm** [comment] 2023-04-01 06:25
This issue is not fixed and has been a problem for the last 2 weeks now. It works when you delete all your files and start new but it seems the first restart it comes back. It is quite disappointing that this issue would be closed without actually fixing anything.

**Comment by MarkKla** [comment] 2023-04-01 06:27
> This issue is not fixed and has been a problem for the last 2 weeks now. It works when you delete all your files and start new but it seems the first restart it comes back. It is quite disappointing that this issue would be closed without actually fixing anything.

Totally agree

**Comment by RickoT** [comment] 2023-04-01 06:31
Also agree, I had to downgrade to 2.9.22 to get everything working again, not sure why this is being closed if it is not working on latest

**Comment by mikeo999** [comment] 2023-04-01 07:49
Yep , I removed it and did a reinstall but same problem. So now deleted it and switch to Cloudflare Tunnels.

**Comment by alexonpeace** [comment] 2023-04-02 18:09
why is this closed, the issue still exists or is there some other fix I didn't find about

**Comment by sanurielf** [comment] 2023-04-03 02:08
Same issue here. Why is this ticket closed?

**Comment by Zackery** [comment] 2023-04-03 04:55
> Just editing my comment to let you know that pruning the cert folder worked for me:
> 
> 
> 
> ```
> 
>  docker exec -ti npm_app cert-prune
> 
> ```
> 
> 
> 
> npm_app is the name of my docker container for the jc21/nginx-proxy-manager:latest image. Change it according to your environment.
> 
> 
> 
> 

This worked for me. Let's see how long it lasts!

**Comment by MarkKla** [comment] 2023-04-03 07:46
> > Just editing my comment to let you know that pruning the cert folder worked for me:
> > ```
> > 
> >  docker exec -ti npm_app cert-prune
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > npm_app is the name of my docker container for the jc21/nginx-proxy-manager:latest image. Change it according to your environment.
> 
> This worked for me. Let's see how long it lasts! I am going to look at Traefik as an alternative

I have tried this, not working for me.

**Comment by Bovive** [comment] 2023-04-06 16:05
> Just editing my comment to let you know that pruning the cert folder worked for me:
> 
> ```
>  docker exec -ti npm_app cert-prune
> ```
> 
> npm_app is the name of my docker container for the jc21/nginx-proxy-manager:latest image. Change it according to your environment.

It did prune, but did not fix the issue for me unfortunately.

**Comment by kosmonot** [comment] 2023-04-06 18:12
My letsencrypt directories are pruned and I'm still experiencing this issue (since 2.9.21) on my rpi arm64s when the device is rebooted or docker is updated/restarted.  If I restart the npm container after the intial timeout error it functions normally however, so this is not a super-critical issue for me (more of an OCD annoyance).

 I noticed that compared to my x86 containers (which finish the pull in seconds)  a docker pull of the npm image on rpi arm64s  takes at least 4-5 mins to extract all the elements of the downloaded image. It gets stuck exctracting a few elements midway through for several minutes and then continues throught the list comparatively quickly.  While it's stuck the iowait of the CPU is high (35%-85%) while the cpu is only at ~25%. 

I understand that the container image is not being repulled on every docker restart, but maybe this arm64 slow pull behavior might offer a clue as to what is causing the timeout issue.

**Comment by sduensin** [comment] 2023-04-07 00:07
x86_64 here.  Same error as everyone else.  Rolled back to 2.9.22.

**Comment by nocomment-bln** [comment] 2023-04-07 16:14
also got this error.

**Comment by X4V1** [comment] 2023-04-08 18:11
> My letsencrypt directories are pruned and I'm still experiencing this issue (since 2.9.21) on my rpi arm64s when the device is rebooted or docker is updated/restarted. If I restart the npm container after the intial timeout error it functions normally 

I observed the same thing on my end. I have a raspberry pi 3b+ running debian 11 (raspbian). The version 2.9.22 works fine on the 32bits os (can restart after a reboot without any issue) but not on the 64 bits (getting the timeout with s6 already mentionned). I tried the version 2.9.19 on the 64 bits and that seems to work without issue even after a restart.

I don't understand why the version 2.9.22 is not working on the 64 bits as it works on the 32 bits of raspbian. I will continue to investigate what I can. I also tried to prune certs and it makes no difference.

**Comment by Bovive** [comment] 2023-04-12 21:18
> > My letsencrypt directories are pruned and I'm still experiencing this issue (since 2.9.21) on my rpi arm64s when the device is rebooted or docker is updated/restarted. If I restart the npm container after the intial timeout error it functions normally
> 
> I observed the same thing on my end. I have a raspberry pi 3b+ running debian 11 (raspbian). The version 2.9.22 works fine on the 32bits os (can restart after a reboot without any issue) but not on the 64 bits (getting the timeout with s6 already mentionned). I tried the version 2.9.19 on the 64 bits and that seems to work without issue even after a restart.
> 
> I don't understand why the version 2.9.22 is not working on the 64 bits as it works on the 32 bits of raspbian. I will continue to investigate what I can. I also tried to prune certs and it makes no difference.
> 
> @jc21 do you prefer that we open a new issue for that ? This issue seems to be more about problems related to version 2.10.x so I think we are in front of 2 different problems (one happening linked to the new version issue and the other one for the version 2.9.22 that is not working after a restart on raspbian (debian 11) 64 bits).

Thanks. Going back to 2.9.19 worked for me with Ubuntu 64 bit. I tried 2.9.22 but it didn't work as you said.

**Comment by X4V1** [comment] 2023-04-15 09:58
> Thanks. Going back to 2.9.19 worked for me with Ubuntu 64 bit. I tried 2.9.22 but it didn't work as you said.

Apparently the problem has been introduced in the version 2.9.21. The version 2.9.20 is working fine too.
There was another issue opened (#2743) for that with the exact same issue (can't reboot the container for version > 2.9.20).
Now both issues are closed but it is not fixed yet. I don't know why both were closed as the problem is still there.

**Comment by lreynolds188** [comment] 2023-04-30 00:24
Ran into this bug and was resolved by opening and closing docker-compose.yml. For some reason it was in use by root despite not being opened since last restart.

**Comment by jtrosper** [comment] 2023-05-02 04:12
@jc21 - this issue needs to be reopened.

**Comment by gVes** [comment] 2023-05-07 10:05
I’m very new to the self hosted scene, and thought I had setup my container wrong. 
I’m on rpi arm64 and the container always needs a restart after I reboot the rpi. V2.10.2

**Comment by CrazyWolf13** [comment] 2023-05-07 11:53
Why is this closed?
It still happens on the pi 3b 32bit

**Comment by kosmonot** [comment] 2023-05-11 20:09
npm appears to be functioning properly on my rpi64s now on new 2.10.3 version.  No issues with reboot or docker restart anymore!

**Comment by vlfldr** [comment] 2023-05-11 20:54
can confirm this issue persisted for months and seems to be gone after updating today

**Comment by GamingAstronamy** [comment] 2023-05-14 05:51
Updating to 2.10.3 completely fixed this issue for me as well

**Comment by sanurielf** [comment] 2023-05-15 11:32
Same here. Version 2.10.3 seems to be working ok. Thanks!
