### ISSUE TITLE
can't get ssl

### ISSUE THREAD

**Issue by chatofking** [NginxProxyManager/nginx-proxy-manager#2217] opened 2022-08-24 06:31 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  -  No
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

when i try to get SSL
it show
```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --cert-name "npm-12" --agree-tos --authenticator webroot --email "myemail" --preferred-challenges "dns,http" --domains "mydomain" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (node:child_process:399:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket. (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe. (node:net:687:12)

```
**Nginx Proxy Manager Version**

v2.9.18 © 2022 [jc21.com]
**To Reproduce**
1. Go to nginx proxy manager
2. Click on Add Let's Encrypt Certificate
3. Scroll down to save

**Expected behavior**

i want to get SSL for my ghost blog stack in portainer

**Screenshots**

**Operating System**

Rpi Debian 11 bulleye

**Additional context**

**Comment by the1ts** [comment] 2022-08-24 23:08
Not much to go on, letsencrypt has failed to get to your NPM too many times and has put you on a temporary blacklist.

**Comment by victorcbr** [comment] 2022-08-25 17:01
same error here :/

**Comment by tfmm** [comment] 2022-08-26 01:17
Seeing the same problem here. Just a failure to download the .well-known file.

**Comment by tfmm** [comment] 2022-08-26 01:30
Here's the letsencrypt.log entries for a failed renewal: 

```
2022-08-26 01:24:29,775:DEBUG:certbot._internal.error_handler:Calling registered functions
2022-08-26 01:24:29,776:INFO:certbot._internal.auth_handler:Cleaning up challenges
2022-08-26 01:24:29,776:DEBUG:certbot._internal.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/5mCq1rVr3oIWGpOHjcwZKRr29XjnU0qGDxVhMJPFYWw
2022-08-26 01:24:29,776:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2022-08-26 01:24:29,776:ERROR:certbot._internal.renewal:Failed to renew certificate npm-28 with error: Some challenges have failed.
2022-08-26 01:24:29,777:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/renewal.py", line 484, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1541, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 129, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/renewal.py", line 344, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/client.py", line 442, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/client.py", line 510, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2022-08-26 01:24:29,777:DEBUG:certbot._internal.display.obj:Notifying user:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
```

Nothing has changed with my network or external firewall, and all services behind NPM are fully reachable from the internet as far as I can tell.

**Comment by the1ts** [comment] 2022-08-26 09:22
There is a bug fixed by #2038, if you are using force SSL, turn it off, try a renew and then turn back on. The problem is letsencrypt get pushed to SSL for renew traffic, this fails since letsencrypt does this work over HTTP only.

**Comment by tfmm** [comment] 2022-08-26 11:25
> There is a bug fixed by #2038, if you are using force SSL, turn it off, try a renew and then turn back on. The problem is letsencrypt get pushed to SSL for renew traffic, this fails since letsencrypt does this work over HTTP only.

This did resolve it for me, hopefully that PR gets reviewed/merged soon.

**Comment by chatofking** [comment] 2022-08-27 07:39
where can i see
  Saving debug log to **/var/log/letsencrypt/letsencrypt.log**
i got
[ Directory '/var/log/letsencrypt' does not exist ]

**Comment by the1ts** [comment] 2022-08-27 08:31
@chatofking where are you looking for /var/log/letsencrypt, this would probably be inside the docker container, not on the host since the standard install method does not have /var/log/letsencrypt on a docker volume.

**Comment by chatofking** [comment] 2022-08-28 04:14
where can I find it inside the docker container dir?

**Comment by chatofking** [comment] 2022-08-28 05:14
oh I need to mkdir volume

**Comment by the1ts** [comment] 2022-08-28 11:55
docker exec -it "nginxproxymanager container name" will get you inside the docker container. Or as you say put /var/log/ in a volume.

**Comment by chatofking** [comment] 2022-08-29 06:56
do you know how to export file ?
i try to cp to USB 
/var/log]# cp -R letsencrypt /mnt/usb
cp: cannot overwrite non-directory '/mnt/usb' with directory 'letsencrypt'

**Comment by the1ts** [comment] 2022-08-29 07:57
I think you want to use `docker cp` from outside the container.

**Comment by victorcbr** [comment] 2022-08-29 13:56
> same error here :/

i solved my problem using the duckdns provider.

**Closed** 2022-08-29 23:44 UTC
Labels: bug

**Comment by victorcbr** [comment] 2022-09-01 03:08
duckdns on my public ip, router with forward port and ssl with dns challenge ( just put the token and voilà ).

thanks for support 👏 🙏
